# Stable features
newline_style = "Unix"
max_width = 120
use_small_heuristics = "Max"
use_field_init_shorthand = true

# Unstable features (nightly only)
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
